# quiz_data.py

"""
Quiz data for the 'Caucus Compass' political ideology quiz.
Includes:
- Faction names
- Question text
- Scoring matrix (20x8)
"""

FACTIONS = [
    "Progressive Caucus",
    "New Democrat Coalition",
    "Blue Dog Coalition",
    "Mainstream Democrats",
    "Freedom Caucus",
    "Republican Study Committee",
    "Main Street Caucus",
    "Problem Solvers Caucus",
]

# -------------------------------------------------
# Question text
# -------------------------------------------------
QUESTIONS = {
    1: "The government should heavily tax the rich to reduce inequality.",
    2: "Regulations often hurt small businesses more than large corporations.",
    3: "The U.S. should reduce its military presence overseas.",
    4: "Abortion should be legal and accessible in all states.",
    5: "Border security should be significantly strengthened before any immigration reform.",
    6: "Climate change is a top national security threat.",
    7: "It’s more important for politicians to stand by their principles than to compromise.",
    8: "America’s cultural decline is a bigger threat than economic inequality.",
    9: "The federal budget deficit is a major concern that needs to be reduced.",
    10: "Large corporations have too much power over both parties.",
    11: "The U.S. should provide military and financial support to Ukraine.",
    12: "Police funding should be reduced and redirected to social programs.",
    13: "Congress should work across the aisle to pass bipartisan legislation.",
    14: "Government should play a larger role in healthcare and education.",
    15: "The media and political elite are out of touch with ordinary Americans.",
    16: "Religious values should influence public policy.",
    17: "The U.S. should prioritize domestic manufacturing even if prices rise.",
    18: "Fossil fuels will remain essential for the foreseeable future.",
    19: "College should be free or heavily subsidized.",
    20: "It’s better to shut down the government than agree to a bad spending deal.",
}

# -------------------------------------------------
# Scoring matrix: question_id -> {faction: weight}
# -------------------------------------------------
SCORING = {
    1: {
        "Progressive Caucus": 3,
        "New Democrat Coalition": 1,
        "Blue Dog Coalition": -2,
        "Mainstream Democrats": 1,
        "Freedom Caucus": -3,
        "Republican Study Committee": -2,
        "Main Street Caucus": -1,
        "Problem Solvers Caucus": 0,
    },
    2: {
        "Progressive Caucus": -2,
        "New Democrat Coalition": 2,
        "Blue Dog Coalition": 3,
        "Mainstream Democrats": 0,
        "Freedom Caucus": 3,
        "Republican Study Committee": 2,
        "Main Street Caucus": 2,
        "Problem Solvers Caucus": 1,
    },
    3: {
        "Progressive Caucus": 3,
        "New Democrat Coalition": 0,
        "Blue Dog Coalition": -1,
        "Mainstream Democrats": -1,
        "Freedom Caucus": 2,
        "Republican Study Committee": -2,
        "Main Street Caucus": -1,
        "Problem Solvers Caucus": 0,
    },
    4: {
        "Progressive Caucus": 3,
        "New Democrat Coalition": 2,
        "Blue Dog Coalition": -2,
        "Mainstream Democrats": 2,
        "Freedom Caucus": -3,
        "Republican Study Committee": -2,
        "Main Street Caucus": -1,
        "Problem Solvers Caucus": 1,
    },
    5: {
        "Progressive Caucus": -2,
        "New Democrat Coalition": -1,
        "Blue Dog Coalition": 1,
        "Mainstream Democrats": 0,
        "Freedom Caucus": 3,
        "Republican Study Committee": 2,
        "Main Street Caucus": 2,
        "Problem Solvers Caucus": 0,
    },
    6: {
        "Progressive Caucus": 3,
        "New Democrat Coalition": 2,
        "Blue Dog Coalition": 0,
        "Mainstream Democrats": 1,
        "Freedom Caucus": -3,
        "Republican Study Committee": -2,
        "Main Street Caucus": -1,
        "Problem Solvers Caucus": 1,
    },
    7: {
        "Progressive Caucus": 1,
        "New Democrat Coalition": -2,
        "Blue Dog Coalition": -1,
        "Mainstream Democrats": -2,
        "Freedom Caucus": 3,
        "Republican Study Committee": 2,
        "Main Street Caucus": 1,
        "Problem Solvers Caucus": -3,
    },
    8: {
        "Progressive Caucus": -3,
        "New Democrat Coalition": -1,
        "Blue Dog Coalition": 2,
        "Mainstream Democrats": 0,
        "Freedom Caucus": 3,
        "Republican Study Committee": 3,
        "Main Street Caucus": 2,
        "Problem Solvers Caucus": 0,
    },
    9: {
        "Progressive Caucus": 0,
        "New Democrat Coalition": 1,
        "Blue Dog Coalition": 3,
        "Mainstream Democrats": 2,
        "Freedom Caucus": 2,
        "Republican Study Committee": 3,
        "Main Street Caucus": 3,
        "Problem Solvers Caucus": 2,
    },
    10: {
        "Progressive Caucus": 3,
        "New Democrat Coalition": 0,
        "Blue Dog Coalition": 0,
        "Mainstream Democrats": 1,
        "Freedom Caucus": 2,
        "Republican Study Committee": 1,
        "Main Street Caucus": 0,
        "Problem Solvers Caucus": 2,
    },
    11: {
        "Progressive Caucus": 1,
        "New Democrat Coalition": 2,
        "Blue Dog Coalition": 3,
        "Mainstream Democrats": 2,
        "Freedom Caucus": -2,
        "Republican Study Committee": 2,
        "Main Street Caucus": 2,
        "Problem Solvers Caucus": 3,
    },
    12: {
        "Progressive Caucus": 3,
        "New Democrat Coalition": 0,
        "Blue Dog Coalition": -3,
        "Mainstream Democrats": -1,
        "Freedom Caucus": -3,
        "Republican Study Committee": -3,
        "Main Street Caucus": -2,
        "Problem Solvers Caucus": -1,
    },
    13: {
        "Progressive Caucus": 0,
        "New Democrat Coalition": 2,
        "Blue Dog Coalition": 2,
        "Mainstream Democrats": 2,
        "Freedom Caucus": -2,
        "Republican Study Committee": -1,
        "Main Street Caucus": 3,
        "Problem Solvers Caucus": 3,
    },
    14: {
        "Progressive Caucus": 3,
        "New Democrat Coalition": 2,
        "Blue Dog Coalition": 0,
        "Mainstream Democrats": 1,
        "Freedom Caucus": -3,
        "Republican Study Committee": -2,
        "Main Street Caucus": -1,
        "Problem Solvers Caucus": 1,
    },
    15: {
        "Progressive Caucus": 2,
        "New Democrat Coalition": 0,
        "Blue Dog Coalition": 1,
        "Mainstream Democrats": 0,
        "Freedom Caucus": 3,
        "Republican Study Committee": 2,
        "Main Street Caucus": 2,
        "Problem Solvers Caucus": 2,
    },
    16: {
        "Progressive Caucus": -3,
        "New Democrat Coalition": -2,
        "Blue Dog Coalition": 0,
        "Mainstream Democrats": -1,
        "Freedom Caucus": 3,
        "Republican Study Committee": 3,
        "Main Street Caucus": 2,
        "Problem Solvers Caucus": -1,
    },
    17: {
        "Progressive Caucus": 2,
        "New Democrat Coalition": 2,
        "Blue Dog Coalition": 2,
        "Mainstream Democrats": 2,
        "Freedom Caucus": 3,
        "Republican Study Committee": 2,
        "Main Street Caucus": 2,
        "Problem Solvers Caucus": 2,
    },
    18: {
        "Progressive Caucus": -3,
        "New Democrat Coalition": 0,
        "Blue Dog Coalition": 2,
        "Mainstream Democrats": 0,
        "Freedom Caucus": 3,
        "Republican Study Committee": 3,
        "Main Street Caucus": 2,
        "Problem Solvers Caucus": 1,
    },
    19: {
        "Progressive Caucus": 3,
        "New Democrat Coalition": 1,
        "Blue Dog Coalition": -2,
        "Mainstream Democrats": 0,
        "Freedom Caucus": -3,
        "Republican Study Committee": -2,
        "Main Street Caucus": -1,
        "Problem Solvers Caucus": 0,
    },
    20: {
        "Progressive Caucus": -2,
        "New Democrat Coalition": -2,
        "Blue Dog Coalition": 1,
        "Mainstream Democrats": -2,
        "Freedom Caucus": 3,
        "Republican Study Committee": 2,
        "Main Street Caucus": 0,
        "Problem Solvers Caucus": -3,
    },
}
